version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: cafe-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Deepderin0
      MYSQL_DATABASE: cafemodern
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  cafe-modern:
    build: .
    container_name: cafe-modern
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/cafemodern?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Deepderin0
      JWT_SECRET: "Ze+JmFU6xskoZlBpoqDqr4HEYMgJUiYyntU6Z5g6Ke0="
    volumes:
      - ./uploads:/app/uploads

volumes:
  mysql_data:
